<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Label="NuGet Package Values">
		<IsPackable>true</IsPackable>
		<Title>Purview Event Sourcing</Title>
		<Description>Core abstractions, aggregate types, facades, transactions, and dependency injection extensions for building event-sourced .NET applications.</Description>
		<PackageTags>$(PackageTags);purview;dotnet;event-sourcing;eventstore;event-store;aggregate;domain-driven-design;</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference
			Include="..\SourceGenerator\SourceGenerator.csproj"
			PrivateAssets="all"
			ReferenceOutputAssembly="false"
			OutputItemType="Analyzer"
		/>
		<ProjectReference
			Include="..\SourceGenerator.CodeFixes\SourceGenerator.CodeFixes.csproj"
			PrivateAssets="all"
			ReferenceOutputAssembly="false"
			OutputItemType="Analyzer"
		/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
	</ItemGroup>
</Project>
