namespace Purview.EventSourcing.SourceGenerator.Aggregate;

static partial class AggregateSourceEmitter
{
	public static void GenerateAggregateSource(AggregateEmitContext outputContext, CodeWriter writer)
	{
		outputContext.Debug(
			$"Generating source for aggregate '{outputContext.Aggregate.AggregateClass.Identity.Name}' with {outputContext.Aggregate.Methods.Count} event methods and {outputContext.Aggregate.InvalidMethods.Count} invalid methods."
		);

		writer.AutoGeneratedHeader();

		// Generate event classes in nested event namespaces when commands exist.
		if (outputContext.Aggregate.IsValid && outputContext.Aggregate.Methods.Count > 0)
		{
			foreach (
				var namespaceMethods in outputContext.Aggregate.Methods.GroupBy(
					static method => method.EventType.Identity.Namespace,
					StringComparer.Ordinal
				)
			)
			{
				using (writer.BlockNamespaceScope(namespaceMethods.Key))
				{
					foreach (var method in namespaceMethods)
						GenerateEventClass(outputContext, writer, method);
				}
			}
		}

		// Generate the partial aggregate class in a block-scoped namespace.
		using var nsBlock = writer.BlockNamespaceScope(outputContext.Aggregate.AggregateClass);

		List<IDisposable> containingScopes = new(outputContext.Aggregate.ContainingTypes.Count);
		foreach (var containingType in outputContext.Aggregate.ContainingTypes)
		{
			containingScopes.Add(
				writer.ClassScope(
					new(containingType.Name)
					{
						IsStatic = containingType.IsStatic,
						IsPartial = true,
						GenericTypes = [.. containingType.TypeParameters.Select(static tp => tp.Name)],
					}
				)
			);
		}

		var classAttributes = outputContext.Aggregate.IsValid
			? ImmutableArray.Create(
				new AttributeDeclarationOptions(TypeLibrary.System.Text.Json.Serialization.JsonConverterAttribute)
				{
					Arguments = [new($"typeof({outputContext.Aggregate.AggregateClass.Identity.Name}JsonConverter)")],
				}
			)
			: [];

		writer.Class(
			new(
				outputContext.Aggregate.AggregateClass.Identity,
				outputContext.Aggregate.Accessibility.ToTypeDeclarationAccessibility()
			)
			{
				IsPartial = true,
				IsSealed = false,
				BaseType =
					outputContext.Aggregate.IsValid && outputContext.Aggregate.ShouldDeclareAggregateBase
						? TypeLibrary.Purview.EventSourcing.Aggregates.AggregateBase
						: null,
				Attributes = classAttributes,
				GenericTypes = outputContext.Aggregate.TypeParameters,
			},
			bodyWriter =>
			{
				GenerateJsonSerializationSupport(outputContext, bodyWriter);

				// Generate RegisterEvents override
				GenerateRegisterEvents(outputContext, bodyWriter);

				// Generate Apply methods
				foreach (var method in outputContext.Aggregate.Methods)
					GenerateApplyMethod(bodyWriter, method);

				// Generate command method implementations
				foreach (var method in outputContext.Aggregate.Methods)
				{
					if (method.IsCollectionEvent)
						CollectionCommandMethodEmitter.Generate(bodyWriter, method);
					else
						CommandMethodEmitter.Generate(outputContext, bodyWriter, method);
				}

				GenerateCollectionNormalizationValidationHookDeclarations(outputContext, bodyWriter);
				GeneratePropertyHookDeclarations(outputContext, bodyWriter);

				foreach (var method in outputContext.Aggregate.InvalidMethods)
					GenerateInvalidCommandMethodStub(bodyWriter, method);

				GenerateJsonConverter(outputContext, bodyWriter);
				GenerateJsonModel(outputContext, bodyWriter);
			}
		);

		foreach (var scope in Enumerable.Reverse(containingScopes))
			scope.Dispose();
	}

	static void GenerateRegisterEvents(AggregateEmitContext outputContext, CodeWriter writer)
	{
		writer.Method(
			new("RegisterEvents", TypeDeclarationAccessibility.Protected) { IsOverride = true },
			bodyWriter =>
			{
				foreach (var method in outputContext.Aggregate.Methods)
				{
					bodyWriter.MethodCall("Register", ["Apply"], genericArguments: [method.EventType]);
				}
			}
		);
	}

	static void GenerateJsonSerializationSupport(AggregateEmitContext outputContext, CodeWriter writer)
	{
		TypeIdentity jsonModel = new($"{outputContext.Aggregate.AggregateClass.Identity.Name}JsonModel", null);

		writer.Method(
			new(
				"CreateFromJsonModel",
				new TypeReference(new TypeIdentity(outputContext.Aggregate.AggregateClass.Identity.Name, null)),
				TypeDeclarationAccessibility.Internal
			)
			{
				IsStatic = true,
				Parameters = [new("jsonModel", jsonModel)],
			},
			writeBody =>
			{
				writeBody.Assignment(
					"var aggregate",
					new ObjectCreationOptions(outputContext.Aggregate.AggregateClass)
					{
						InitializerMembers =
						[
							new(
								"Details",
								$"jsonModel.Details ?? new {TypeLibrary.Purview.EventSourcing.Aggregates.AggregateDetails}()"
							),
							.. outputContext.Aggregate.Properties.Select(
								static property => new ObjectInitializerMemberOptions(
									property.PropertyName,
									$"jsonModel.{property.PropertyName}"
								)
							),
						],
					}
				);

				writeBody.Return("aggregate");
			}
		);

		writer.Method(
			new("ToJsonModel", jsonModel, TypeDeclarationAccessibility.Internal),
			writeBody =>
				writeBody
					.OpenBlock(
						"return new()",
						returnBlock =>
						{
							returnBlock.Line("Details = Details,");

							foreach (var property in outputContext.Aggregate.Properties)
							{
								returnBlock
									.Write(property.PropertyName)
									.Write(" = ")
									.Write(property.PropertyName)
									.Line(",");
							}
						}
					)
					.Line(";")
		);
	}

	static void GenerateApplyMethod(CodeWriter writer, AggregateEventMethodInfo method)
	{
		if (method.UserApplyMethodKind == UserApplyMethodKind.NonPartial)
		{
			// User supplied a complete, non-partial Apply(...) implementation.
			return;
		}

		if (method.UserApplyMethodKind == UserApplyMethodKind.PartialImplementation || method.ManualApply)
		{
			// If the user is providing a partial implementation or is manually applying the event, we generate a partial method declaration for Apply(...) with the appropriate accessibility.
			writer.PartialMethod(
				new("Apply", accessibility: method.ManualApply ? method.UserApplyMethodAccessibility : null)
				{
					IsPartial = true,
					Parameters = [new("@event", method.EventType)],
				}
			);

			return;
		}

		if (method.IsCollectionEvent)
		{
			GenerateCollectionApplyMethod(writer, method);
			return;
		}

		const string eventParameterName = "@event";
		var mappedParameters = method.AllParameters.Where(static parameter => parameter.HasAggregateProperty).ToList();

		writer.Method(
			new("Apply", TypeDeclarationAccessibility.Private)
			{
				Parameters = [new(eventParameterName, method.EventType)],
			},
			applyBody =>
			{
				foreach (var prop in mappedParameters)
					applyBody.Assignment("var", $"__previous{prop.AggregatePropertyName}", prop.AggregatePropertyName);

				if (mappedParameters.Count > 0)
					applyBody.NewLine();

				foreach (var prop in mappedParameters)
					applyBody.Assignment(prop.AggregatePropertyName, $"{eventParameterName}.{prop.PropertyName}");

				if (mappedParameters.Count > 0)
					applyBody.NewLine();

				foreach (var prop in mappedParameters)
					applyBody.MethodCall(
						$"On{prop.AggregatePropertyName}Changed",
						[$"__previous{prop.AggregatePropertyName}", prop.AggregatePropertyName]
					);

				applyBody.MethodCall($"OnApplied{GetHookName(method.EventType)}", eventParameterName);
			}
		);
	}

	internal static string GetHookName(TypeReference eventType)
	{
		var eventName = eventType.Identity.Name;
		if (!eventName.EndsWith("Event", StringComparison.Ordinal))
			eventName += "Event";

		return eventName;
	}

	static void GenerateCollectionApplyMethod(CodeWriter writer, AggregateEventMethodInfo method)
	{
		var collectionEvent = method.CollectionEvent!;
		var parameter = method.AllParameters[0];
		const string eventParameterName = "@event";
		var hookSuffix = GetHookName(method.EventType);
		var operationMethod = collectionEvent.Operation == CollectionMutationOperation.Add ? "Add" : "Remove";

		writer.Method(
			new("Apply", TypeDeclarationAccessibility.Private)
			{
				Parameters = [new(eventParameterName, method.EventType)],
			},
			writeBody =>
			{
				writeBody.IfBlock(
					$"{collectionEvent.PropertyName} is null",
					block =>
						block.Throw(
							PurviewTypeLibrary.System.InvalidOperationException,
							$"Collection property '{collectionEvent.PropertyName}' cannot be null when applying {method.EventType}."
						)
				);

				if (collectionEvent.ParameterShape == CollectionParameterShape.Single)
				{
					writeBody.MethodCallOn(
						$"(({PurviewTypeLibrary.System.Collections.Generic.ICollection.MakeGeneric(collectionEvent.ElementType)})"
							+ $"{collectionEvent.PropertyName})",
						operationMethod,
						$"{eventParameterName}.{parameter.PropertyName}"
					);
				}
				else
				{
					writeBody.Block(
						$"foreach (var __item in {eventParameterName}.{parameter.PropertyName})",
						block =>
							block.MethodCallOn(
								$"(({PurviewTypeLibrary.System.Collections.Generic.ICollection.MakeGeneric(collectionEvent.ElementType)})"
									+ $"{collectionEvent.PropertyName})",
								operationMethod,
								"__item"
							)
					);
				}

				writeBody.MethodCall($"OnApplied{hookSuffix}", eventParameterName);
			}
		);
	}

	static void GeneratePropertyHookDeclarations(AggregateEmitContext outputContext, CodeWriter writer)
	{
		var aggregateProperties = outputContext
			.Aggregate.Methods.SelectMany(static method => method.AllParameters)
			.Where(static parameter => parameter.HasAggregateProperty)
			.GroupBy(static parameter => parameter.AggregatePropertyName, StringComparer.Ordinal)
			.Select(static group => group.First())
			.ToList();

		var suppression = CreateCA1822Suppression();
		foreach (var prop in aggregateProperties)
		{
			var changingValueType = prop.RequiresLocalCopy ? prop.PropertyType : prop.ParameterType;
			writer.PartialMethod(
				new($"On{prop.AggregatePropertyName}Changing")
				{
					Attributes = [suppression],
					Parameters = [new(prop.ParameterName, changingValueType, ParameterModifier.Ref)],
				}
			);

			writer.PartialMethod(
				new($"On{prop.AggregatePropertyName}Changed")
				{
					Attributes = [suppression],
					Parameters = [new("previous", prop.PropertyType), new("current", prop.PropertyType)],
				}
			);
		}
	}

	static void GenerateCollectionNormalizationValidationHookDeclarations(
		AggregateEmitContext outputContext,
		CodeWriter writer
	)
	{
		var declaredKeys = new HashSet<string>(StringComparer.Ordinal);
		foreach (var method in outputContext.Aggregate.Methods.Where(static method => method.IsCollectionEvent))
		{
			var collectionEvent = method.CollectionEvent!;
			var parameter = method.AllParameters[0];
			var declarationType =
				collectionEvent.ParameterShape == CollectionParameterShape.Single
					? collectionEvent.ElementType
					: TypeLibrary
						.System.Collections.Generic.IEnumerable.MakeGeneric(collectionEvent.ElementType)
						.AsTypeReference();
			var key = $"{collectionEvent.NormalizeValidateHookSuffix}|{declarationType}";
			if (!declaredKeys.Add(key))
				continue;

			var suppression = CreateCA1822Suppression();
			ParameterDeclarationOptions param = new(parameter.ParameterName, declarationType);
			writer.PartialMethod(
				new($"OnNormalizing{collectionEvent.NormalizeValidateHookSuffix}")
				{
					Attributes = [suppression],
					Parameters = [param with { Modifier = ParameterModifier.Ref }],
				}
			);

			writer.PartialMethod(
				new($"OnValidating{collectionEvent.NormalizeValidateHookSuffix}")
				{
					Attributes = [suppression],
					Parameters = [param with { Modifier = ParameterModifier.Ref }],
				}
			);
		}
	}

	public static AttributeDeclarationOptions CreateCA1822Suppression() =>
		new(PurviewTypeLibrary.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute)
		{
			Arguments =
			[
				new("\"Performance\""),
				new("\"CA1822:Mark members as static\""),
				new(
					"\"Generated partial hook declaration must match instance signature and cannot be static.\"",
					"Justification",
					true
				),
			],
		};

	internal static string GetLocalValueName(EventPropertyInfo parameter) => $"__{parameter.ParameterName}Value";

	internal static ImmutableArray<MethodCallArgumentOptions> BuildOnCreatingCallArgumentList(
		ImmutableArray<EventPropertyInfo> parameters
	) =>
		[
			.. parameters.Select(static parameter => new MethodCallArgumentOptions(
				GetWorkingValueName(parameter),
				ParameterModifier.Ref
			)),
		];

	internal static ImmutableArray<ParameterDeclarationOptions> BuildOnCreatingDeclarationParameterList(
		ImmutableArray<EventPropertyInfo> parameters
	) =>
		[
			.. parameters.Select(static parameter => new ParameterDeclarationOptions(
				parameter.ParameterName,
				parameter.RequiresLocalCopy ? parameter.PropertyType : parameter.ParameterType,
				ParameterModifier.Ref
			)),
		];

	internal static void EmitEventCreation(CodeWriter writer, AggregateEventMethodInfo method, bool declareVariable)
	{
		var initializerMembers = method
			.EventParameters.Select(prop =>
			{
				var valueExpression = GetWorkingValueName(prop);
				if (prop.IsNotNull || prop.IsRequired)
					valueExpression += "!";

				return new ObjectInitializerMemberOptions(prop.PropertyName, valueExpression);
			})
			.ToArray();

		writer.Assignment(
			declareVariable ? "var @event" : "@event",
			new ObjectCreationOptions(method.EventType) { InitializerMembers = [.. initializerMembers] }
		);
	}

	internal static string BuildPropertyValueExpression(
		AggregateEmitContext outputContext,
		AggregateEventMethodInfo method,
		EventPropertyInfo parameter
	)
	{
		return parameter.ParameterConversionKind switch
		{
			EventParameterConversionKind.None => parameter.ParameterName,
			EventParameterConversionKind.Implicit => $"({parameter.PropertyType}){parameter.ParameterName}",
			EventParameterConversionKind.Create => $"{parameter.PropertyType}.Create({parameter.ParameterName})",
			EventParameterConversionKind.ContextualCreate =>
				$"{parameter.PropertyType}.Create({parameter.ParameterName}, new global::Purview.EventSourcing.ValueObjects.ValueObjectContext<{outputContext.Aggregate.AggregateClass}>(this, MemberName: nameof({parameter.AggregatePropertyName}), EventName: nameof({method.EventType})))",
			_ => parameter.ParameterName,
		};
	}

	internal static string BuildUnchangedCondition(List<EventPropertyInfo> parameters)
	{
		return string.Join(" && ", parameters.Select(BuildUnchangedComparison));
	}

	static string BuildUnchangedComparison(EventPropertyInfo parameter)
	{
		var comparisonValue = GetWorkingValueName(parameter);

		return parameter.UseStringOrdinalComparison
			? $"global::System.String.Equals({parameter.AggregatePropertyName}, {comparisonValue}, global::System.StringComparison.Ordinal)"
			: $"global::System.Collections.Generic.EqualityComparer<{parameter.EqualityComparerTypeName}>.Default.Equals({parameter.AggregatePropertyName}, {comparisonValue})";
	}

	internal static string GetWorkingValueName(EventPropertyInfo parameter) =>
		parameter.RequiresLocalCopy ? GetLocalValueName(parameter) : parameter.ParameterName;

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	internal static CodeWriter EmitNoChangeReturn(CodeWriter writer, EventMethodReturnKind returnKind)
	{
		return returnKind switch
		{
			EventMethodReturnKind.Aggregate => writer.Return("this"),
			EventMethodReturnKind.Bool => writer.Return("false"),
			_ => writer.Return(),
		};
	}

	internal static void EmitSuccessReturn(CodeWriter writer, EventMethodReturnKind returnKind)
	{
		if (returnKind == EventMethodReturnKind.Aggregate)
			writer.Return("this");
		else if (returnKind == EventMethodReturnKind.Bool)
			writer.Return("true");
		else
			writer.Return();
	}

	static void GenerateInvalidCommandMethodStub(CodeWriter writer, InvalidAggregateEventMethodInfo method)
	{
		var diagnosticIds = !method.DiagnosticIds.IsEmpty
			? string.Join(", ", method.DiagnosticIds)
			: "unknown diagnostic IDs";
		var message = EscapeStringLiteral(
			$"The generated aggregate event method '{method.Signature}' is unavailable because [Event] validation failed. Review the suppressed generator diagnostics for this method ({diagnosticIds})."
		);

		using (writer.OpenBlockScope(method.Signature))
		{
			writer.Throw($"new global::System.InvalidOperationException(\"{message}\")");
		}
		writer.NewLine();
	}

	static string EscapeStringLiteral(string value) =>
		value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n")
			.Replace("\t", "\\t");

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	internal static TypeDeclarationAccessibility GetAccessModifier(Accessibility accessibility)
	{
		return accessibility switch
		{
			Accessibility.Public => TypeDeclarationAccessibility.Public,
			Accessibility.Private => TypeDeclarationAccessibility.Private,
			Accessibility.Internal => TypeDeclarationAccessibility.Internal,
			Accessibility.Protected => TypeDeclarationAccessibility.Protected,
			Accessibility.ProtectedOrInternal => TypeDeclarationAccessibility.ProtectedInternal,
			Accessibility.ProtectedAndInternal => TypeDeclarationAccessibility.PrivateProtected,
			_ => TypeDeclarationAccessibility.Internal,
		};
	}

	static void GenerateJsonConverter(AggregateEmitContext outputContext, CodeWriter writer)
	{
		TypeIdentity jsonModel = new($"{outputContext.Aggregate.AggregateClass.Identity.Name}JsonModel", null);

		writer.Class(
			new($"{outputContext.Aggregate.AggregateClass.Identity.Name}JsonConverter")
			{
				IsPartial = false,
				IsSealed = true,
				BaseType = TypeLibrary.System.Text.Json.Serialization.JsonConverter.MakeGeneric(
					outputContext.Aggregate.AggregateClass
				),
			},
			bodyWriter =>
			{
				bodyWriter.Method(
					new(
						"Read",
						outputContext.Aggregate.AggregateClass.Nullable(writer),
						TypeDeclarationAccessibility.Public
					)
					{
						IsOverride = true,
						Parameters =
						[
							new("reader", TypeLibrary.System.Text.Json.Utf8JsonReader, ParameterModifier.Ref),
							new("typeToConvert", PurviewTypeLibrary.System.Type),
							new("options", TypeLibrary.System.Text.Json.JsonSerializerOptions),
						],
					},
					methodWriter =>
					{
						methodWriter.Assignment(
							"var",
							"jsonModel",
							writeValue =>
								writeValue.MethodCall(
									"Deserialize",
									[new MethodCallArgumentOptions("reader", ParameterModifier.Ref), "options"],
									receiver: $"{TypeLibrary.System.Text.Json.JsonSerializer}",
									genericArguments: [jsonModel]
								)
						);

						methodWriter.IfBlock(
							"jsonModel is null",
							ifBlock =>
								ifBlock.Throw(
									TypeLibrary.System.Text.Json.JsonException,
									$"Unable to deserialize {outputContext.Aggregate.AggregateClass}."
								)
						);

						methodWriter.Return(writerExpression =>
							writerExpression.MethodCallOn(
								$"{outputContext.Aggregate.AggregateClass.Identity}",
								"CreateFromJsonModel",
								"jsonModel"
							)
						);
					}
				);

				bodyWriter.Method(
					new("Write", TypeDeclarationAccessibility.Public)
					{
						IsOverride = true,
						Parameters =
						[
							new("writer", TypeLibrary.System.Text.Json.Utf8JsonWriter),
							new("value", outputContext.Aggregate.AggregateClass),
							new("options", TypeLibrary.System.Text.Json.JsonSerializerOptions),
						],
					},
					methodWriter =>
						methodWriter.MethodCallOn(
							$"{TypeLibrary.System.Text.Json.JsonSerializer}",
							"Serialize",
							"writer",
							"value.ToJsonModel()",
							"options"
						)
				);
			}
		);
	}

	static void GenerateJsonModel(AggregateEmitContext outputContext, CodeWriter writer)
	{
		writer.Class(
			new(
				$"{outputContext.Aggregate.AggregateClass.Identity.Name}JsonModel",
				TypeDeclarationAccessibility.Internal
			)
			{
				IsPartial = false,
				IsSealed = true,
			},
			bodyWriter =>
			{
				bodyWriter.Property(
					new(
						"Details",
						TypeLibrary.Purview.EventSourcing.Aggregates.AggregateDetails.MakeNullable(bodyWriter),
						TypeDeclarationAccessibility.Public
					)
					{
						HasSetter = true,
						Initializer = "new()",
					}
				);
				foreach (var property in outputContext.Aggregate.Properties)
				{
					bodyWriter.Property(
						new(property.PropertyName, property.PropertyType, TypeDeclarationAccessibility.Public)
						{
							HasSetter = true,
							Initializer = "default!",
						}
					);
				}
			}
		);
	}
}
