// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Purview.EventSourcing.SqlServer.Snapshots.EntityFramework;

#nullable disable

namespace Purview.EventSourcing.SqlServer.Snapshots.EntityFramework.Migrations
{
    [DbContext(typeof(SnapshotStoreDBContext))]
    [Migration("20260412000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Purview.EventSourcing.SqlServer.Snapshot.EntityFramework.SnapshotStoreEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("AggregateType")
                        .HasDatabaseName("IX_Snapshots_AggregateType");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AggregateType"), new[] { "Payload" });

                    b.ToTable("Snapshots", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
