// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Purview.EventSourcing.SqlServer.Events.EntityFramework;

#nullable disable

namespace Purview.EventSourcing.SqlServer.Events.EntityFramework.Migrations
{
    [DbContext(typeof(EventStoreDbContext))]
    partial class EventStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Purview.EventSourcing.SqlServer.Events.EntityFramework.EventStoreEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CausationId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdempotencyId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Payload")
                        .HasColumnType("json");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AggregateId", "AggregateType", "EntityType")
                        .HasDatabaseName("IX_EventStore_AggregateId_EntityType");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AggregateId", "AggregateType", "EntityType"), new[] { "Version", "IsDeleted" });

                    b.HasIndex("AggregateId", "AggregateType", "Version")
                        .HasDatabaseName("IX_EventStore_EventRange")
                        .HasFilter("[EntityType] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AggregateId", "AggregateType", "Version"), new[] { "Payload", "EventType", "IdempotencyId", "SchemaVersion", "CorrelationId", "CausationId", "UserId", "Timestamp" });

                    b.HasIndex("AggregateType", "EntityType", "IsDeleted")
                        .HasDatabaseName("IX_EventStore_AggregateType_EntityType");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AggregateType", "EntityType", "IsDeleted"), new[] { "AggregateId" });

                    b.ToTable("EventStore", "dbo");
                });
        }
    }
}
