using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Purview.EventSourcing.SourceGenerator.Common;

/// <summary>
/// Serialization, parsing, and emission of the deterministic event-contract manifest.
/// The JSON shape is compact and stable: entries are sorted ordinally and no timestamps,
/// absolute paths, machine information, random values, or culture-sensitive formatting are
/// ever included.
/// </summary>
static class EventContractManifestLibrary
{
	public const int FormatVersion = 1;

	public const string BaselineFileName = "EventContractManifest.json";

	public const string BaselineFileNameProperty = "PurviewEventContractBaselineFileName";

	public const string ManifestEnabledProperty = "PurviewEventContractManifestEnabled";

	public const string GeneratedHintName = "EventContractManifest.g.cs";

	public static string CreateAggregateKey(string aggregateNamespace, string aggregateName) =>
		$"{aggregateNamespace}\0{aggregateName}";

	public static string CreateEventKey(string aggregateNamespace, string aggregateName, string methodName) =>
		$"{aggregateNamespace}\0{aggregateName}\0{methodName}";

	public static EventContractManifest BuildManifest(EquatableArray<AggregateContract> contracts)
	{
		var sorted = contracts
			.OrderBy(static contract => contract.AggregateNamespace, StringComparer.Ordinal)
			.ThenBy(static contract => contract.AggregateName, StringComparer.Ordinal)
			.Select(static contract => new AggregateContract(
				contract.AggregateName,
				contract.AggregateNamespace,
				new EquatableArray<EventContractEntry>([
					.. contract
						.Events.OrderBy(static e => e.EventName, StringComparer.Ordinal)
						.ThenBy(static e => e.EventNamespace, StringComparer.Ordinal)
						.ThenBy(static e => e.SchemaVersion)
						.ThenBy(static e => e.MethodName, StringComparer.Ordinal),
				])
			))
			.ToImmutableArray();

		return new(FormatVersion, new(sorted));
	}

	public static string Serialize(EventContractManifest manifest)
	{
		var builder = new StringBuilder(1024);
		builder.Append("{\"formatVersion\":");
		builder.Append(manifest.FormatVersion.ToString(System.Globalization.CultureInfo.InvariantCulture));
		builder.Append(",\"aggregates\":[");
		var aggregateIndex = 0;
		foreach (var aggregate in manifest.Aggregates)
		{
			if (aggregateIndex++ > 0)
				builder.Append(',');

			builder.Append("{\"name\":");
			AppendString(builder, aggregate.AggregateName);
			builder.Append(",\"namespace\":");
			AppendString(builder, aggregate.AggregateNamespace);
			builder.Append(",\"events\":[");
			var eventIndex = 0;
			foreach (var entry in aggregate.Events)
			{
				if (eventIndex++ > 0)
					builder.Append(',');

				builder.Append("{\"name\":");
				AppendString(builder, entry.EventName);
				builder.Append(",\"namespace\":");
				AppendString(builder, entry.EventNamespace);
				builder.Append(",\"method\":");
				AppendString(builder, entry.MethodName);
				builder.Append(",\"schemaVersion\":");
				builder.Append(entry.SchemaVersion.ToString(System.Globalization.CultureInfo.InvariantCulture));
				builder.Append(",\"fields\":[");
				var fieldIndex = 0;
				foreach (var field in entry.Fields)
				{
					if (fieldIndex++ > 0)
						builder.Append(',');

					builder.Append("{\"name\":");
					AppendString(builder, field.Name);
					builder.Append(",\"type\":");
					AppendString(builder, field.Type);
					builder.Append(",\"elementType\":");
					AppendNullableString(builder, field.ElementType);
					builder.Append(",\"isArray\":");
					AppendBoolean(builder, field.IsArray);
					builder.Append(",\"isNullable\":");
					AppendBoolean(builder, field.IsNullable);
					builder.Append(",\"isRequired\":");
					AppendBoolean(builder, field.IsRequired);
					builder.Append(",\"isString\":");
					AppendBoolean(builder, field.IsString);
					builder.Append('}');
				}

				builder.Append("]}");
			}

			builder.Append("]}");
		}

		builder.Append("]}");
		return builder.ToString();
	}

	/// <summary>
	/// Parses a baseline manifest. Returns a <see cref="BaselineState"/> carrying either a
	/// parsed manifest or an actionable parse error; it never throws.
	/// </summary>
	public static BaselineState Parse(string json, string fileName)
	{
		var parser = new ManifestParser(json, fileName);
		try
		{
			return parser.Parse();
		}
		catch (ManifestParseException ex)
		{
			return new BaselineState(null, new BaselineError(ex.Message));
		}
	}

	public static SourceText EmitSource(EventContractManifest manifest)
	{
		var json = Serialize(manifest);
		var escaped = json.Replace("\\", "\\\\").Replace("\"", "\\\"");

		var builder = new StringBuilder(256 + escaped.Length);
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();
		builder.AppendLine("namespace Purview.EventSourcing.Generated");
		builder.AppendLine("{");
		builder.AppendLine("	/// <summary>");
		builder.AppendLine("	/// The deterministic event-contract manifest for this compilation.");
		builder.AppendLine(
			"	/// Register it at startup with AddEventContractManifest to enable runtime and Admin inspection."
		);
		builder.AppendLine("	/// </summary>");
		builder.AppendLine("	public static class EventContractManifest");
		builder.AppendLine("	{");
		builder.AppendLine("		/// <summary>The manifest format version.</summary>");
		builder.AppendLine(
			$"		public const int FormatVersion = {manifest.FormatVersion.ToString(System.Globalization.CultureInfo.InvariantCulture)};"
		);
		builder.AppendLine();
		builder.AppendLine("		/// <summary>The event-contract manifest serialized as compact JSON.</summary>");
		builder.AppendLine("		public const string Json =");
		builder.AppendLine($"			\"{escaped}\";");
		builder.AppendLine("	}");
		builder.AppendLine("}");

		return SourceText.From(builder.ToString(), Encoding.UTF8);
	}

	static void AppendString(StringBuilder builder, string value)
	{
		builder.Append('"');
		foreach (var c in value)
		{
			switch (c)
			{
				case '"':
					builder.Append("\\\"");
					break;
				case '\\':
					builder.Append("\\\\");
					break;
				case '\b':
					builder.Append("\\b");
					break;
				case '\f':
					builder.Append("\\f");
					break;
				case '\n':
					builder.Append("\\n");
					break;
				case '\r':
					builder.Append("\\r");
					break;
				case '\t':
					builder.Append("\\t");
					break;
				default:
					if (c < 0x20)
						builder
							.Append("\\u")
							.Append(((int)c).ToString("x4", System.Globalization.CultureInfo.InvariantCulture));
					else
						builder.Append(c);
					break;
			}
		}

		builder.Append('"');
	}

	static void AppendNullableString(StringBuilder builder, string? value)
	{
		if (value is null)
			builder.Append("null");
		else
			AppendString(builder, value);
	}

	static void AppendBoolean(StringBuilder builder, bool value) => builder.Append(value ? "true" : "false");

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1032:Implement standard exception constructors")]
	public sealed class ManifestParseException(string message) : Exception(message);

	sealed class ManifestParser(string json, string fileName)
	{
		int _position;

		public BaselineState Parse()
		{
			SkipWhitespace();
			var manifest = ReadRootObject();
			if (manifest.FormatVersion != FormatVersion)
			{
				return new(
					null,
					new BaselineError(
						$"baseline '{fileName}' declares format version {manifest.FormatVersion.ToString(System.Globalization.CultureInfo.InvariantCulture)}, but this generator supports version {FormatVersion.ToString(System.Globalization.CultureInfo.InvariantCulture)}. Regenerate the baseline with the current version of the package."
					)
				);
			}

			// The parser should have consumed the entire input; if not, it's an error.
			return new(manifest, null);
		}

		EventContractManifest ReadRootObject()
		{
			Expect('{');

			int? formatVersion = null;
			var aggregates = ImmutableArray.CreateBuilder<AggregateContract>();

			ReadProperties(propertyName =>
			{
				switch (propertyName)
				{
					case "formatVersion":
						formatVersion = ReadInteger();
						break;
					case "aggregates":
						aggregates.AddRange(ReadAggregates());
						break;
					default:
						SkipValue();
						break;
				}
			});

			if (formatVersion is null)
				throw Error("the root object is missing the required 'formatVersion' property");

			// The aggregates property is optional; if it's missing, the manifest is empty.
			return new EventContractManifest(formatVersion.Value, new(aggregates.ToImmutable()));
		}

		ImmutableArray<AggregateContract> ReadAggregates()
		{
			var builder = ImmutableArray.CreateBuilder<AggregateContract>();
			Expect('[');
			SkipWhitespace();
			if (TryConsume(']'))
				return builder.ToImmutable();

			while (true)
			{
				builder.Add(ReadAggregate());
				SkipWhitespace();
				if (TryConsume(']'))
					break;

				Expect(',');
			}

			return builder.ToImmutable();
		}

		AggregateContract ReadAggregate()
		{
			Expect('{');

			var name = string.Empty;
			var @namespace = string.Empty;
			var events = ImmutableArray.CreateBuilder<EventContractEntry>();

			ReadProperties(propertyName =>
			{
				switch (propertyName)
				{
					case "name":
						name = ReadString();
						break;
					case "namespace":
						@namespace = ReadString();
						break;
					case "events":
						events.AddRange(ReadEvents());
						break;
					default:
						SkipValue();
						break;
				}
			});

			if (string.IsNullOrEmpty(name))
				throw Error("an aggregate is missing the required 'name' property");
			if (string.IsNullOrEmpty(@namespace))
				throw Error($"aggregate '{name}' is missing the required 'namespace' property");

			// The events property is optional; if it's missing, the aggregate has no events.
			return new AggregateContract(name, @namespace, new(events.ToImmutable()));
		}

		ImmutableArray<EventContractEntry> ReadEvents()
		{
			var builder = ImmutableArray.CreateBuilder<EventContractEntry>();
			Expect('[');
			SkipWhitespace();
			if (TryConsume(']'))
				return builder.ToImmutable();

			while (true)
			{
				builder.Add(ReadEvent());
				SkipWhitespace();
				if (TryConsume(']'))
					break;

				Expect(',');
			}

			return builder.ToImmutable();
		}

		EventContractEntry ReadEvent()
		{
			Expect('{');

			var name = string.Empty;
			var @namespace = string.Empty;
			var method = string.Empty;
			int? schemaVersion = null;
			var fields = ImmutableArray.CreateBuilder<EventContractField>();

			ReadProperties(propertyName =>
			{
				switch (propertyName)
				{
					case "name":
						name = ReadString();
						break;
					case "namespace":
						@namespace = ReadString();
						break;
					case "method":
						method = ReadString();
						break;
					case "schemaVersion":
						schemaVersion = ReadInteger();
						break;
					case "fields":
						fields.AddRange(ReadFields());
						break;
					default:
						SkipValue();
						break;
				}
			});

			if (string.IsNullOrEmpty(name))
				throw Error("an event is missing the required 'name' property");
			if (string.IsNullOrEmpty(@namespace))
				throw Error($"event '{name}' is missing the required 'namespace' property");
			if (string.IsNullOrEmpty(method))
				throw Error($"event '{name}' is missing the required 'method' property");
			if (schemaVersion is null)
				throw Error($"event '{name}' is missing the required 'schemaVersion' property");
			if (schemaVersion < 1)
				throw Error(
					$"event '{name}' declares schema version {schemaVersion}, which must be greater than or equal to 1"
				);

			// The fields property is optional; if it's missing, the event has no fields.
			return new EventContractEntry(name, @namespace, method, schemaVersion.Value, new(fields.ToImmutable()));
		}

		ImmutableArray<EventContractField> ReadFields()
		{
			var builder = ImmutableArray.CreateBuilder<EventContractField>();
			Expect('[');
			SkipWhitespace();
			if (TryConsume(']'))
				return builder.ToImmutable();

			while (true)
			{
				builder.Add(ReadField());
				SkipWhitespace();
				if (TryConsume(']'))
					break;

				Expect(',');
			}

			return builder.ToImmutable();
		}

		EventContractField ReadField()
		{
			Expect('{');

			var name = string.Empty;
			var type = string.Empty;
			string? elementType = null;
			var isArray = false;
			var isNullable = false;
			var isRequired = false;
			var isString = false;

			ReadProperties(propertyName =>
			{
				switch (propertyName)
				{
					case "name":
						name = ReadString();
						break;
					case "type":
						type = ReadString();
						break;
					case "elementType":
						elementType = ReadNullableString();
						break;
					case "isArray":
						isArray = ReadBooleanValue();
						break;
					case "isNullable":
						isNullable = ReadBooleanValue();
						break;
					case "isRequired":
						isRequired = ReadBooleanValue();
						break;
					case "isString":
						isString = ReadBooleanValue();
						break;
					default:
						SkipValue();
						break;
				}
			});

			if (string.IsNullOrEmpty(name))
				throw Error("a field is missing the required 'name' property");
			if (string.IsNullOrEmpty(type))
				throw Error($"field '{name}' is missing the required 'type' property");

			// The elementType property is optional; if it's missing, the field has no element type.
			return new EventContractField(name, type, elementType, isArray, isNullable, isRequired, isString);
		}

		void ReadProperties(Action<string> onProperty)
		{
			SkipWhitespace();
			if (TryConsume('}'))
				return;

			while (true)
			{
				SkipWhitespace();
				var propertyName = ReadString();
				SkipWhitespace();
				Expect(':');
				onProperty(propertyName);

				SkipWhitespace();
				if (TryConsume('}'))
					break;

				Expect(',');
			}
		}

		void SkipValue()
		{
			SkipWhitespace();
			if (TryConsume('{'))
			{
				SkipUntilValueEnd('{', '}');
				return;
			}

			if (TryConsume('['))
			{
				SkipUntilValueEnd('[', ']');
				return;
			}

			// string
			if (Peek() == '"')
			{
				ReadString();
				return;
			}

			// number / true / false / null
			while (true)
			{
				var c = Peek();
				if (c is ',' or '}' or ']' or '\0')
					return;

				_position++;
			}
		}

		void SkipUntilValueEnd(char open, char close)
		{
			var depth = 1;
			var inString = false;
			while (depth > 0)
			{
				var c = Peek();
				if (c == '\0')
					throw Error($"unterminated value (missing '{close}')");

				_position++;
				if (inString)
				{
					if (c == '\\')
					{
						if (Peek() == '\0')
							throw Error("unterminated string escape");
						_position++;
					}
					else if (c == '"')
					{
						inString = false;
					}

					continue;
				}

				if (c == open)
				{
					depth++;
				}
				else if (c == close)
				{
					depth--;
				}
				else if (c == '"')
				{
					inString = true;
				}
			}
		}

		int ReadInteger()
		{
			SkipWhitespace();
			var start = _position;
			if (TryConsume('-'))
				start = _position;

			var digits = 0;
			while (Peek() is >= '0' and <= '9')
			{
				_position++;
				digits++;
			}

			if (digits == 0)
				throw Error("expected an integer");

			if (
				int.TryParse(
					json.Substring(start, _position - start),
					System.Globalization.NumberStyles.Integer,
					System.Globalization.CultureInfo.InvariantCulture,
					out var value
				)
			)
				return value;

			// The number is too large to fit in a 32-bit integer.
			throw Error($"'{json.Substring(start, _position - start)}' is not a valid 32-bit integer");
		}

		string ReadNullableString()
		{
			SkipWhitespace();
			if (TryConsume("null"))
				return null!;

			// The value is not null, so it must be a string.
			return ReadString();
		}

		bool ReadBooleanValue()
		{
			SkipWhitespace();
			if (TryConsume("true"))
				return true;
			if (TryConsume("false"))
				return false;

			// The value is not a boolean, so it's an error.
			throw Error("expected a boolean value");
		}

		string ReadString()
		{
			SkipWhitespace();
			if (Peek() != '"')
				throw Error("expected a string value");

			_position++;
			var builder = new StringBuilder();
			while (true)
			{
				var c = Peek();
				if (c == '\0')
					throw Error("unterminated string");
				if (c == '"')
				{
					_position++;
					return builder.ToString();
				}

				_position++;
				if (c != '\\')
				{
					builder.Append(c);
					continue;
				}

				var escape = Peek();
				if (escape == '\0')
					throw Error("unterminated string escape");

				_position++;
				switch (escape)
				{
					case '"':
						builder.Append('"');
						break;
					case '\\':
						builder.Append('\\');
						break;
					case '/':
						builder.Append('/');
						break;
					case 'b':
						builder.Append('\b');
						break;
					case 'f':
						builder.Append('\f');
						break;
					case 'n':
						builder.Append('\n');
						break;
					case 'r':
						builder.Append('\r');
						break;
					case 't':
						builder.Append('\t');
						break;
					case 'u':
						if (_position + 4 > json.Length)
							throw Error("unterminated unicode escape");
						var hex = json.Substring(_position, 4);
						if (
							!ushort.TryParse(
								hex,
								System.Globalization.NumberStyles.HexNumber,
								System.Globalization.CultureInfo.InvariantCulture,
								out var code
							)
						)
							throw Error($"invalid unicode escape '\\u{hex}'");
						_position += 4;
						builder.Append((char)code);
						break;
					default:
						throw Error($"unknown string escape '\\{escape}'");
				}
			}
		}

		void Expect(char expected)
		{
			SkipWhitespace();
			if (Peek() != expected)
				throw Error(
					$"expected '{expected}' but found '{(Peek() == '\0' ? "end of file" : Peek().ToString())}'"
				);

			_position++;
		}

		bool TryConsume(char expected)
		{
			SkipWhitespace();
			if (Peek() != expected)
				return false;

			_position++;
			return true;
		}

		bool TryConsume(string expected)
		{
			SkipWhitespace();
			if (json.IndexOf(expected, _position, StringComparison.Ordinal) == _position)
			{
				_position += expected.Length;
				return true;
			}

			return false;
		}

		void SkipWhitespace()
		{
			while (_position < json.Length && char.IsWhiteSpace(json[_position]))
				_position++;
		}

		char Peek() => _position < json.Length ? json[_position] : '\0';

		ManifestParseException Error(string message) =>
			new($"baseline '{fileName}' could not be parsed at position {_position}: {message}");
	}
}
