<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\EventSourcing\EventSourcing.csproj" />
		<ProjectReference Include="..\Validation.FluentValidation\Validation.FluentValidation.csproj" />
		<ProjectReference Include="..\Validation.ZodSharp\Validation.ZodSharp.csproj" />
		<!-- Direct reference required when not used via a NuGet package -->
		<ProjectReference
			Include="..\SourceGenerator\SourceGenerator.csproj"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="false"
			PrivateAssets="all"
		/>
		<ProjectReference
			Include="..\EntityFrameworkCore.SourceGenerator\EntityFrameworkCore.SourceGenerator.csproj"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="false"
			PrivateAssets="all"
		/>
	</ItemGroup>
</Project>
